version: "3.2"
services:
  codex-accounting-dev:
    build:
      dockerfile: "docker/Dockerfile.dev"
      context: .
    user: "node"
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
    stdin_open: true
    tty: true
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.2
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017

volumes:
  mongodata:
