version: "3.4"

services:
  codex-accounting-prod:
    build:
      dockerfile: "docker/Dockerfile.prod"
      context: .
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    network_mode: host
    volumes:
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.2
    env_file:
      - .env
