name: Build and Push

on: [push]

env:
  DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/codex-accounting

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_REPO }}
          tag_with_ref: true
          dockerfile: docker/Dockerfile.prod
          push: ${{ endsWith(github.ref, '/stage') || endsWith(github.ref, '/prod') }}

      - name: Deploy stage
      if: endsWith(github.ref, '/stage')
      run: |
        curl -X POST -H "Content-Type: application/json" --data "{\"branch\":\"${GITHUB_REF##*/}\",\"secret_token\":\"${{ secrets.DEPLOY_TOKEN }}\"}" ${{ secrets.DEPLOY_ADDRESS }}

