name: Build and deploy

on: [push]

env:
  DOCKER_USERNAME: codexteamuser
  DOCKER_REPO: ${{ env.DOCKERHUB_USERNAME }}/codex-accounting

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_REPO }}
          tag_with_ref: true
          push: ${{ endsWith(github.ref, '/stage') || endsWith(github.ref, '/prod') }}
