name: Run Jest tests on push

on:
  - push

jobs:
  mongodb:
    runs-on: ubuntu-latest
    name: Test mongo-action
    steps:
      - name: Create mongo Docker container
        id: build_mongo_docker
        uses: DigiPie/mongo-action@v1.0.0
        with:
          image-version: latest
          port: 27017
      - name: Install mongodb-clients
        id: install_mongodb_clients
        run: sudo apt install mongodb-clients
      - name: Test mongo connection
        id: test_mongo_connection
        run: "sudo mongo localhost:27017"
  build:
    name: Run Jest tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install mongodb
        run: sudo apt install -y mongodb
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test
      - uses: codecov/codecov-action@v1

